# Generated by Django 5.0 on 2026-04-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizattempt',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
