# Generated by Django 5.0 on 2026-04-29 03:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_file_type'),
        ('quizzes', '0003_userquizattempt_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['quiz', 'order'], name='idx_question_quiz_order'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['user', '-created_at'], name='idx_quiz_user_created'),
        ),
        migrations.AddIndex(
            model_name='userquizattempt',
            index=models.Index(fields=['user', 'quiz', '-created_at'], name='idx_attempt_user_quiz'),
        ),
    ]
