# Generated by Django 5.0 on 2026-05-03 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_file_type'),
        ('quizzes', '0004_question_idx_question_quiz_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='documents.document'),
        ),
    ]
