# Generated by Django 5.0 on 2026-09-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_alter_quiz_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='duration_minutes',
            field=models.IntegerField(default=15, help_text='Thời gian làm bài tính theo phút (0 = không giới hạn)'),
        ),
        migrations.AddField(
            model_name='userquizattempt',
            name='time_spent_seconds',
            field=models.IntegerField(default=0, help_text='Thời gian hoàn thành tính bằng giây'),
        ),
    ]
