# Generated by Django 5.0 on 2026-09-25 14:10

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_idx_doc_filename_trgm'),
        ('quizzes', '0006_quiz_duration_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quiz',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass('title', name='gin_trgm_ops'), name='idx_quiz_title_trgm'),
        ),
    ]
