# Generated by Django 5.0 on 2026-09-28 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_quiz_idx_quiz_title_trgm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('remember', '1. Nhớ (Remember) - Nhắc lại kiến thức, định nghĩa'), ('understand', '2. Hiểu (Understand) - Giải thích ý nghĩa, so sánh'), ('apply', '3. Áp dụng (Apply) - Vận dụng vào thực tế, tính toán'), ('analyze', '4. Phân tích (Analyze) - Chia nhỏ vấn đề, quan hệ nhân quả'), ('evaluate', '5. Đánh giá (Evaluate) - Nhận xét, phán đoán, tiêu chí'), ('create', '6. Sáng tạo (Create) - Tổng hợp, đề xuất giải pháp mới'), ('basic', 'Cơ Bản (Tổng hợp Nhớ & Hiểu)'), ('advanced', 'Nâng Cao (Tổng hợp Áp dụng & Phân tích)')], default='basic', max_length=20),
        ),
        migrations.CreateModel(
            name='ReviewCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('box_level', models.IntegerField(default=1)),
                ('next_review_at', models.DateTimeField(db_index=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_count', models.IntegerField(default=0)),
                ('is_mastered', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_cards', to='quizzes.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review_cards',
                'ordering': ['next_review_at', 'box_level'],
                'indexes': [models.Index(fields=['user', 'next_review_at'], name='idx_rev_user_next'), models.Index(fields=['user', 'box_level'], name='idx_rev_user_box')],
                'unique_together': {('user', 'question')},
            },
        ),
    ]
