# Generated by Django 5.0 on 2026-09-28 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_alter_quiz_difficulty_reviewcard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcard',
            name='custom_first_interval_hours',
            field=models.IntegerField(default=1, help_text='Số giờ ôn lại cho Ngăn 1 ở chế độ ngắn hạn (VD: 1, 2, 4, 6 giờ)'),
        ),
        migrations.AddField(
            model_name='reviewcard',
            name='review_mode',
            field=models.CharField(choices=[('short_term', 'Ngắn hạn (< 1 tuần, tính bằng giờ)'), ('long_term', 'Dài hạn (1 tuần - 1 tháng)')], default='short_term', max_length=20),
        ),
        migrations.AddIndex(
            model_name='reviewcard',
            index=models.Index(fields=['user', 'review_mode'], name='idx_rev_user_mode'),
        ),
    ]
