# Generated by Django 5.0 on 2026-10-02 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_reviewcard_custom_first_interval_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizattempt',
            name='quiz_title',
            field=models.CharField(blank=True, default='', help_text='Lưu cố định tên đề thi lúc làm bài, chống mất dữ liệu khi đề gốc bị xóa', max_length=255),
        ),
        migrations.AlterField(
            model_name='userquizattempt',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='quizzes.quiz'),
        ),
    ]
