# Generated by Django 5.0 on 2026-09-25 14:09

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_file_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='document',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass('filename', name='gin_trgm_ops'), name='idx_doc_filename_trgm'),
        ),
    ]
